### ISSUE TITLE
Add possibility to subscribe within a date range

### ISSUE THREAD

**Issue by cdene** [okainov/munich-scripts#46] opened 2020-09-15 09:45 UTC
Might be useful to add a new function as a subscription for available appointments for a certain date frame in the future. 
For users who already know, they have to do something within a certain timeframe but there are no appointments at that stage

**Comment by okainov** [comment] 2020-09-15 10:31
Thanks for the report!

However isn't it a duplicate of https://github.com/okainov/munich-scripts/issues/10 which was actually implemented (but not merged yet :() in #39?

**Comment by cdene** [comment] 2020-09-15 12:16
Yeah seems that way. In #10 only a right bound used, aka deadline. Would be great to add an ability to select also a start date of an interval (within  #39 datetime.datetime.now() has been used)
Would be great if #39 could be merged though

**Comment by okainov** [comment] 2022-07-24 19:14
I think with #39 and #70 it's good enough now, I don't really the the case to "find termins *later* than X"... Feel free to share the use case and reopen if it's not right though!

**Closed as completed by okainov** 2022-07-24 19:14 UTC
